pub mod audio_input;
pub mod audio_output;
pub mod config;
pub mod metronome;
pub mod note;
pub mod pitch_detection;
pub mod protocol;
pub mod protocol_io;
pub mod reference_tone;
mod shared_audio;
pub mod tuning_library;
